[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "--cov=webapi --cov-report=html"
testpaths = ["webapi/tests"]